#!/bin/sh

# geoip-update-free – Update the local copy of Maxmind GeoLite Free database
#
# Copyright © 2013 Johan Kiviniemi <devel@johan.kiviniemi.name>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -eu

dir_base=/usr/local/share/GeoIP
dir_dl="$dir_base/download"

uri_base='http://geolite.maxmind.com/download/geoip/database'

download() {
  local path uri
  path="$1"; shift
  uri="$1"; shift

  >&2 printf 'Downloading %s\n' "$uri"

  if [ -e "$path" ]; then
    curl --time-cond "$path" --remote-time --output "$path" --url "$uri"
  else
    curl --remote-time --output "$path" --url "$uri"
  fi
}

umask 022

mkdir -pv "$dir_base" "$dir_dl"

for f in GeoLiteCountry/GeoIP.dat.gz GeoIPv6.dat.gz GeoLiteCity.dat.gz \
         GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz asnum/GeoIPASNum.dat.gz \
         asnum/GeoIPASNumv6.dat.gz
do
  f_unp="${f%.gz}"

  uri="$uri_base/$f"
  path_dl="$dir_dl/${f#*/}"
  path_temp="$dir_dl/${f_unp#*/}.temp"
  path_unp="$dir_base/${f_unp#*/}"

  download "$path_dl" "$uri"
  if ! [ -e "$path_unp" ] || [ "$path_dl" -nt "$path_unp" ]; then
    >&2 printf 'Updating %s\n' "$path_unp"

    gunzip -c -- "$path_dl" >"$path_temp"
    touch -r "$path_dl" -- "$path_temp"
    chmod 0644 -- "$path_temp"
    mv -f -- "$path_temp" "$path_unp"
  fi
done
